# Use root/example as user/password credentials

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
volumes:
  mariadb:
